name: Generate Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: generate-pacman-svg
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - uses: skp8500/PAC-CONTRIBUTIONS@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
